# Generated by Django 5.0.4 on 2024-04-16 23:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applicants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="resume",
        ),
    ]
