# Generated by Django 5.0.4 on 2024-04-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicants", "0002_remove_application_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(default=None, upload_to="resumes/"),
        ),
    ]
